
name: Playwright Tests

on:
  push:
    branches: [tests-fai]
  pull_request:
    branches: [tests-fai]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - uses: actions/checkout@v4

    # Paso 2: Configurar Node.js
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # Paso 3: Instalar dependencias
    - name: Install dependencies
      run: npm ci

    # Paso 4: Instalar los navegadores de Playwright
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Paso 5: Establecer el Proxy
    - name: Set Proxy for Playwright
      run: |
        # Obtener lista de proxies desde el repositorio de PROXY-List
        PROXIES=$(curl https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/proxy-list-raw.txt)
        
        # Seleccionar un proxy aleatorio de la lista
        PROXY=$(echo "$PROXIES" | shuf -n 1)
        
        echo "Usando el proxy: $PROXY"
        
        # Crear archivo .proxy-env y guardar la configuración del proxy
        echo "SELECTED_PROXY=http://$PROXY" > .proxy-env
        
        # Mostrar contenido del archivo para verificación
        cat .proxy-env

    # Paso 6: Ejecutar las pruebas de Playwright
    - name: Run Playwright tests
      run: npx playwright test

    # Paso 7: Subir el reporte de las pruebas
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
