
name: Playwright Tests

on:
  push:
    branches: [tests-fai]
  pull_request:
    branches: [tests-fai]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - uses: actions/checkout@v4

    # Paso 2: Configurar Node.js
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # Paso 3: Instalar dependencias
    - name: Install dependencies
      run: npm ci

    # Paso 4: Instalar los navegadores de Playwright
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # Paso 6: Ejecutar las pruebas de Playwright
    - name: Run Playwright tests
      run: npx playwright test

    # Paso 7: Subir el reporte de las pruebas
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
